name: job-value-pass
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
      output3: ${{ steps.step2.outputs.output3 }}
    steps:
      - id: step1
        run: echo "output1=hello" >> $GITHUB_OUTPUT

      - id: step2
        run: |
          echo "output2=world" >> $GITHUB_OUTPUT
          echo "output3=!!" >> $GITHUB_OUTPUT

      - id: echo
        run: |
          echo ${{ steps.step1.outputs.output1 }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}
