name: job-dependencies
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first-job finished."
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - run: echo "second-job finished."
  third-job:
    needs: [ first-job, second-job ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "third-job finished."
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job finished."
