name: job-dependencies
on:
  workflow_dispatch:
jobs:
  job1-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1-1 finished."
  job1-2:
    needs: job1-1
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1-2 finished."
  job1-3:
    needs: job1-2
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1-3 finished."
  job2-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2-1 finished."
  job2-2:
    needs: [ job1-2, job2-1 ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2-2 finished."
