name: workflow-a
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        options:
          - dev
          - prod
jobs:
  kick-workflow-b:
    uses: .github/workflows/workflow-b.yml
    with:
      env: ${{ github.event.inputs.env }}
