name: workflow-job-switch-by-event
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 21 * * *'
  pull_request:
    types: [opened, closed]
jobs:
  run-only-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ${{ github.base_ref }} == 'main' ] && [ ${{ github.head_ref }} == 'create-sample-workflows' ]; then
            echo "compound condition"
          fi
  run-only-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          if [ ${{ github.event.pull_request.merged }} == 'true' ]; then
            echo "This PR is merged."
          else
            echo "This PR is not merged."
          fi
      - name: step-2
        if: ${{ github.event.pull_request.merged == false }}
        run: |
          if [ ${{ github.event.pull_request.merged }} == 'true' ]; then
            echo "This PR is merged."
          else
            echo "This PR is not merged."
          fi
