name: workflow-job-switch-by-event
on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed]
jobs:
  run-only-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          value1=1
          value2=2
          if [ $value1 == 1 ] && [ $value2 == 2 ]; then
            echo "compound condition"
          fi
  run-only-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          if [ ${{ github.event.pull_request.merged }} == 'true' ]; then
            echo "This PR is merged."
          else
            echo "This PR is not merged."
          fi
      - name: step-2
        if: ${{ github.event.pull_request.merged == false }}
        run: |
          if [ ${{ github.event.pull_request.merged }} == 'true' ]; then
            echo "This PR is merged."
          else
            echo "This PR is not merged."
          fi
